name: CI
on:
  push: 
    branches: [develop, main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: app
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
      redis:
        image: redis:7
        ports: ['6379:6379']
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      mailhog:
        image: mailhog/mailhog:v1.0.1
        ports: ['1025:1025', '8025:8025']

    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
          
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'pnpm'
          
      - name: Copy environment file
        run: cp .env.example .env
        
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Lint code
        run: pnpm lint
        
      - name: Type check
        run: pnpm typecheck
        
      - name: Run tests
        run: pnpm test
        env:
          CI: true
          
      - name: Build application
        run: pnpm build
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/app
          REDIS_URL: redis://localhost:6379
          
      - name: Update status.md timestamp
        if: success() && github.ref == 'refs/heads/main'
        run: |
          # Update the last updated timestamp in status.md
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          sed -i "s/\*\*Last Updated:\*\* [0-9-]* [0-9:]* UTC/\*\*Last Updated:\*\* $TIMESTAMP/g" status.md
          
          # Update CI health status based on build results
          sed -i 's/- \*\*Lint:\*\* .*/- \*\*Lint:\*\* ✅ Passes/' status.md
          sed -i 's/- \*\*Typecheck:\*\* .*/- \*\*Typecheck:\*\* ✅ Passes/' status.md  
          sed -i 's/- \*\*Build:\*\* .*/- \*\*Build:\*\* ✅ Passes/' status.md
          
          # Commit and push if changes were made
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet status.md; then
            git add status.md
            git commit -m "chore: update status.md timestamp and CI status [skip ci]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-artifacts
          path: |
            .next/
            playwright-report/
            coverage/
          retention-days: 30