name: CI
on:
  push: 
    branches: [develop, main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: app
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
      redis:
        image: redis:7
        ports: ['6379:6379']
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      mailhog:
        image: mailhog/mailhog:v1.0.1
        ports: ['1025:1025', '8025:8025']

    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with: 
          version: 9
          
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'pnpm'
          
      - name: Copy environment file
        run: cp .env.example .env
        
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Lint code
        run: pnpm lint
        
      - name: Type check
        run: pnpm typecheck
        
      - name: Run tests
        run: pnpm test
        env:
          CI: true
          
      - name: Build application
        run: pnpm build
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/app
          REDIS_URL: redis://localhost:6379
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-artifacts
          path: |
            .next/
            playwright-report/
            coverage/
          retention-days: 30