name: CI
on:
  push: 
    branches: [develop, main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: app
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
      redis:
        image: redis:7
        ports: ['6379:6379']
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      mailhog:
        image: mailhog/mailhog:v1.0.1
        ports: ['1025:1025', '8025:8025']

    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
          
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'pnpm'
          
      - name: Copy environment file
        run: cp .env.example .env
        
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Lint code
        run: pnpm lint
        
      - name: Type check
        run: pnpm typecheck
        
      - name: Run tests
        run: pnpm test
        env:
          CI: true
          
      - name: Build application
        run: pnpm build
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/app
          REDIS_URL: redis://localhost:6379
          
      - name: Update status.md with CI results
        if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        run: |
          # Set git configuration
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Use the enhanced automation script
          chmod +x ./scripts/update-status.sh ./scripts/git-status-ops.sh
          
          # Update status based on job result
          if [ "${{ job.status }}" = "success" ]; then
            ./scripts/update-status.sh ci-success
          else
            ./scripts/update-status.sh ci-failure
          fi
          
          # Commit and push if changes were made  
          if ! git diff --quiet status.md; then
            git add status.md
            git commit -m "chore(ci): auto-update status.md - $(date -u '+%Y-%m-%d %H:%M UTC') [skip ci]"
            git push
          else
            echo "No changes to status.md"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-artifacts
          path: |
            .next/
            playwright-report/
            coverage/
          retention-days: 30